type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
  userType: String
}

type Vendor @table {
  name: String!
  cuisineType: String!
  address: String!
  createdAt: Timestamp!
  description: String
  phoneNumber: String
  website: String
  imageUrl: String
  user: User
}

type MenuItem @table {
  name: String!
  price: Float!
  createdAt: Timestamp!
  description: String
  imageUrl: String
  category: String
  vendor: Vendor
}

type OperatingHour @table {
  dayOfWeek: String!
  openingTime: String!
  closingTime: String!
  isClosed: Boolean
  vendor: Vendor
}

type Location @table {
  latitude: Float!
  longitude: Float!
  createdAt: Timestamp!
  name: String
  vendor: Vendor
}